//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using Albion.Db.Xml.Entity.Building;
using Albion.Db.Xml.Entity.Common;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class craftingrequirements {
    
    private craftingrequirementsCraftresource[] craftresourceField;
    
    private string timeField;
    
    private string silverinrvpercentageField;
    

    [System.Xml.Serialization.XmlElementAttribute("craftresource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public craftingrequirementsCraftresource[] craftresource {
        get {
            return this.craftresourceField;
        }
        set {
            this.craftresourceField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string silverinrvpercentage {
        get {
            return this.silverinrvpercentageField;
        }
        set {
            this.silverinrvpercentageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class craftingrequirementsCraftresource {
    
    private string uniquenameField;
    
    private string countField;
    
    private string usedinrepairField;
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string usedinrepair {
        get {
            return this.usedinrepairField;
        }
        set {
            this.usedinrepairField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class favoritedish {
    
    private favoritedishDish[] dishField;
    

    [System.Xml.Serialization.XmlElementAttribute("dish", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public favoritedishDish[] dish {
        get {
            return this.dishField;
        }
        set {
            this.dishField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class favoritedishDish {
    
    private string itemField;
    
    private string bonusField;
    
    private string weightField;
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bonus {
        get {
            return this.bonusField;
        }
        set {
            this.bonusField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class journal {
    
    private string uniquenameField;
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsBankbuilding {
    
    private string uniquenameField;
    
    private string tierField;
    
    private string iconAtlasField;
    
    private string iconSpriteField;
    
    private string hideonclustermapField;
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconAtlas {
        get {
            return this.iconAtlasField;
        }
        set {
            this.iconAtlasField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconSprite {
        get {
            return this.iconSpriteField;
        }
        set {
            this.iconSpriteField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hideonclustermap {
        get {
            return this.hideonclustermapField;
        }
        set {
            this.hideonclustermapField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsBlackmarketbuilding {
    
    private AudioInfo[] audioInfoField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string iconAtlasField;
    
    private string iconSpriteField;
    
    private string hideonclustermapField;
    
    private string usesbuildingplacementrulesField;
    

    [System.Xml.Serialization.XmlElementAttribute("AudioInfo")]
    public AudioInfo[] AudioInfo {
        get {
            return this.audioInfoField;
        }
        set {
            this.audioInfoField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconAtlas {
        get {
            return this.iconAtlasField;
        }
        set {
            this.iconAtlasField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconSprite {
        get {
            return this.iconSpriteField;
        }
        set {
            this.iconSpriteField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hideonclustermap {
        get {
            return this.hideonclustermapField;
        }
        set {
            this.hideonclustermapField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string usesbuildingplacementrules {
        get {
            return this.usesbuildingplacementrulesField;
        }
        set {
            this.usesbuildingplacementrulesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsBuildingreference {
    
    private string templateField;
    
    private string uniquenameField;
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string template {
        get {
            return this.templateField;
        }
        set {
            this.templateField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsCastlegate {
    
    private string uniquenameField;
    
    private string tierField;
    
    private string durabilityField;
    
    private string recoverytimeField;
    
    private string uispritenameField;
    
    private string surnameField;
    
    private string descriptionlocatagField;
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durability {
        get {
            return this.durabilityField;
        }
        set {
            this.durabilityField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string recoverytime {
        get {
            return this.recoverytimeField;
        }
        set {
            this.recoverytimeField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uispritename {
        get {
            return this.uispritenameField;
        }
        set {
            this.uispritenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string descriptionlocatag {
        get {
            return this.descriptionlocatagField;
        }
        set {
            this.descriptionlocatagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsFactionbuilding {
    
    private CraftingItemList[] craftingitemlistField;
    
    private AudioInfo[] audioInfoField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string questgivertypeField;
    
    private string namegeneratorField;
    
    private string craftanimationField;
    
    private string factionField;
    
    private string uisoundeventField;
    
    private string iconAtlasField;
    
    private string iconSpriteField;
    
    private string uispritenameField;
    
    private string hideonclustermapField;
    

    [System.Xml.Serialization.XmlElementAttribute("craftingitemlist")]
    public CraftingItemList[] craftingitemlist {
        get {
            return this.craftingitemlistField;
        }
        set {
            this.craftingitemlistField = value;
        }
    }
    

    [System.Xml.Serialization.XmlElementAttribute("AudioInfo")]
    public AudioInfo[] AudioInfo {
        get {
            return this.audioInfoField;
        }
        set {
            this.audioInfoField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string questgivertype {
        get {
            return this.questgivertypeField;
        }
        set {
            this.questgivertypeField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string namegenerator {
        get {
            return this.namegeneratorField;
        }
        set {
            this.namegeneratorField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string craftanimation {
        get {
            return this.craftanimationField;
        }
        set {
            this.craftanimationField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string faction {
        get {
            return this.factionField;
        }
        set {
            this.factionField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uisoundevent {
        get {
            return this.uisoundeventField;
        }
        set {
            this.uisoundeventField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconAtlas {
        get {
            return this.iconAtlasField;
        }
        set {
            this.iconAtlasField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconSprite {
        get {
            return this.iconSpriteField;
        }
        set {
            this.iconSpriteField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uispritename {
        get {
            return this.uispritenameField;
        }
        set {
            this.uispritenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hideonclustermap {
        get {
            return this.hideonclustermapField;
        }
        set {
            this.hideonclustermapField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsFarmbuilding {
    
    private buildingsFarmbuildingBuildablegroundsBuildableground[] buildablegroundsField;
    
    private craftingrequirements[] craftingrequirementsField;
    
    private buildingsFarmbuildingFarmableitemsFarmableitem[] farmableitemsField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string placecostField;
    
    private string durabilityField;
    
    private string durabilitylossField;
    
    private string categoryField;
    
    private string displaygroupField;
    
    private string unlockedField;
    
    private string iconAtlasField;
    
    private string iconSpriteField;
    
    private string uispritenameField;
    
    private string accessrightspresetField;
    
    private string repaircostfactorField;
    
    private string destructionreturnfactorField;
    

    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("buildableground", typeof(buildingsFarmbuildingBuildablegroundsBuildableground), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public buildingsFarmbuildingBuildablegroundsBuildableground[] buildablegrounds {
        get {
            return this.buildablegroundsField;
        }
        set {
            this.buildablegroundsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("farmableitem", typeof(buildingsFarmbuildingFarmableitemsFarmableitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public buildingsFarmbuildingFarmableitemsFarmableitem[] farmableitems {
        get {
            return this.farmableitemsField;
        }
        set {
            this.farmableitemsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placecost {
        get {
            return this.placecostField;
        }
        set {
            this.placecostField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durability {
        get {
            return this.durabilityField;
        }
        set {
            this.durabilityField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durabilityloss {
        get {
            return this.durabilitylossField;
        }
        set {
            this.durabilitylossField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displaygroup {
        get {
            return this.displaygroupField;
        }
        set {
            this.displaygroupField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlocked {
        get {
            return this.unlockedField;
        }
        set {
            this.unlockedField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconAtlas {
        get {
            return this.iconAtlasField;
        }
        set {
            this.iconAtlasField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconSprite {
        get {
            return this.iconSpriteField;
        }
        set {
            this.iconSpriteField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uispritename {
        get {
            return this.uispritenameField;
        }
        set {
            this.uispritenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string accessrightspreset {
        get {
            return this.accessrightspresetField;
        }
        set {
            this.accessrightspresetField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string repaircostfactor {
        get {
            return this.repaircostfactorField;
        }
        set {
            this.repaircostfactorField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string destructionreturnfactor {
        get {
            return this.destructionreturnfactorField;
        }
        set {
            this.destructionreturnfactorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsFarmbuildingBuildablegroundsBuildableground {
    
    private string groundField;
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ground {
        get {
            return this.groundField;
        }
        set {
            this.groundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsFarmbuildingFarmableitemsFarmableitem {
    
    private string uniquenameField;
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsLabourer {
    
    private journal[] journalssoldField;
    
    private journal[] journalsacceptedField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string namegeneratorField;
    
    private string hirepriceField;
    
    private string settleintimeField;
    
    private string fametoprogressField;
    
    private string joblengthField;
    
    private string yieldmultiplierField;
    
    private string happinessmovementtickrateField;
    
    private string happinessunitsafterhireField;
    
    private string maxbedcontributionField;
    
    private string maxtablecontributionField;
    
    private string maxtrophycontributionField;
    
    private string happinessunitsField;
    
    private string professionField;
    
    private string upgradeabletoField;
    
    private string durabilityField;
    
    private string durabilitylossField;
    
    private string nutritionstorageField;
    
    private string nutritionlossField;
    
    private string displaygroupField;
    
    private string unlockedField;
    
    private string iconAtlasField;
    
    private string iconSpriteField;
    
    private string avatarField;
    
    private string avatarringField;
    
    private string accessrightspresetField;
    

    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("journal", typeof(journal), IsNullable=false)]
    public journal[] journalssold {
        get {
            return this.journalssoldField;
        }
        set {
            this.journalssoldField = value;
        }
    }
    

    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("journal", typeof(journal), IsNullable=false)]
    public journal[] journalsaccepted {
        get {
            return this.journalsacceptedField;
        }
        set {
            this.journalsacceptedField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string namegenerator {
        get {
            return this.namegeneratorField;
        }
        set {
            this.namegeneratorField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hireprice {
        get {
            return this.hirepriceField;
        }
        set {
            this.hirepriceField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string settleintime {
        get {
            return this.settleintimeField;
        }
        set {
            this.settleintimeField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fametoprogress {
        get {
            return this.fametoprogressField;
        }
        set {
            this.fametoprogressField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string joblength {
        get {
            return this.joblengthField;
        }
        set {
            this.joblengthField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string yieldmultiplier {
        get {
            return this.yieldmultiplierField;
        }
        set {
            this.yieldmultiplierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string happinessmovementtickrate {
        get {
            return this.happinessmovementtickrateField;
        }
        set {
            this.happinessmovementtickrateField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string happinessunitsafterhire {
        get {
            return this.happinessunitsafterhireField;
        }
        set {
            this.happinessunitsafterhireField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxbedcontribution {
        get {
            return this.maxbedcontributionField;
        }
        set {
            this.maxbedcontributionField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxtablecontribution {
        get {
            return this.maxtablecontributionField;
        }
        set {
            this.maxtablecontributionField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxtrophycontribution {
        get {
            return this.maxtrophycontributionField;
        }
        set {
            this.maxtrophycontributionField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string happinessunits {
        get {
            return this.happinessunitsField;
        }
        set {
            this.happinessunitsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string profession {
        get {
            return this.professionField;
        }
        set {
            this.professionField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string upgradeableto {
        get {
            return this.upgradeabletoField;
        }
        set {
            this.upgradeabletoField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durability {
        get {
            return this.durabilityField;
        }
        set {
            this.durabilityField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durabilityloss {
        get {
            return this.durabilitylossField;
        }
        set {
            this.durabilitylossField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionstorage {
        get {
            return this.nutritionstorageField;
        }
        set {
            this.nutritionstorageField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionloss {
        get {
            return this.nutritionlossField;
        }
        set {
            this.nutritionlossField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displaygroup {
        get {
            return this.displaygroupField;
        }
        set {
            this.displaygroupField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlocked {
        get {
            return this.unlockedField;
        }
        set {
            this.unlockedField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconAtlas {
        get {
            return this.iconAtlasField;
        }
        set {
            this.iconAtlasField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconSprite {
        get {
            return this.iconSpriteField;
        }
        set {
            this.iconSpriteField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string avatar {
        get {
            return this.avatarField;
        }
        set {
            this.avatarField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string avatarring {
        get {
            return this.avatarringField;
        }
        set {
            this.avatarringField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string accessrightspreset {
        get {
            return this.accessrightspresetField;
        }
        set {
            this.accessrightspresetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsMarketplacebuilding {
    
    private AudioInfo[] audioInfoField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string iconAtlasField;
    
    private string iconSpriteField;
    
    private string hideonclustermapField;
    
    private string usesbuildingplacementrulesField;
    

    [System.Xml.Serialization.XmlElementAttribute("AudioInfo")]
    public AudioInfo[] AudioInfo {
        get {
            return this.audioInfoField;
        }
        set {
            this.audioInfoField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconAtlas {
        get {
            return this.iconAtlasField;
        }
        set {
            this.iconAtlasField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconSprite {
        get {
            return this.iconSpriteField;
        }
        set {
            this.iconSpriteField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hideonclustermap {
        get {
            return this.hideonclustermapField;
        }
        set {
            this.hideonclustermapField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string usesbuildingplacementrules {
        get {
            return this.usesbuildingplacementrulesField;
        }
        set {
            this.usesbuildingplacementrulesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsMeldbuilding {
    
    private favoritedishDish[] favoritedishField;
    
    private CraftingItemList[] craftingitemlistField;
    
    private buildingsMeldbuildingMeldingcombinationsCombination[] meldingcombinationsField;
    
    private craftingrequirements[] craftingrequirementsField;
    
    private AudioInfo[] audioInfoField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string placecostField;
    
    private string durabilityField;
    
    private string durabilitylossField;
    
    private string nutritionstorageField;
    
    private string nutritionlossField;
    
    private string craftcapacityField;
    
    private string craftcapacityregenerationField;
    
    private string categoryField;
    
    private string displaygroupField;
    
    private string defaultcostfactorfriendsField;
    
    private string defaultcostfactorusersField;
    
    private string craftanimationField;
    
    private string iconAtlasField;
    
    private string iconSpriteField;
    
    private string uispritenameField;
    
    private string uisoundeventField;
    
    private string unlockedField;
    
    private string accessrightspresetField;
    

    [System.Xml.Serialization.XmlArrayItemAttribute("dish", typeof(favoritedishDish), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public favoritedishDish[] favoritedish {
        get {
            return this.favoritedishField;
        }
        set {
            this.favoritedishField = value;
        }
    }
    

    [System.Xml.Serialization.XmlElementAttribute("craftingitemlist")]
    public CraftingItemList[] craftingitemlist {
        get {
            return this.craftingitemlistField;
        }
        set {
            this.craftingitemlistField = value;
        }
    }
    

    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("combination", typeof(buildingsMeldbuildingMeldingcombinationsCombination), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public buildingsMeldbuildingMeldingcombinationsCombination[] meldingcombinations {
        get {
            return this.meldingcombinationsField;
        }
        set {
            this.meldingcombinationsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlElementAttribute("AudioInfo")]
    public AudioInfo[] AudioInfo {
        get {
            return this.audioInfoField;
        }
        set {
            this.audioInfoField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placecost {
        get {
            return this.placecostField;
        }
        set {
            this.placecostField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durability {
        get {
            return this.durabilityField;
        }
        set {
            this.durabilityField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durabilityloss {
        get {
            return this.durabilitylossField;
        }
        set {
            this.durabilitylossField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionstorage {
        get {
            return this.nutritionstorageField;
        }
        set {
            this.nutritionstorageField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionloss {
        get {
            return this.nutritionlossField;
        }
        set {
            this.nutritionlossField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string craftcapacity {
        get {
            return this.craftcapacityField;
        }
        set {
            this.craftcapacityField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string craftcapacityregeneration {
        get {
            return this.craftcapacityregenerationField;
        }
        set {
            this.craftcapacityregenerationField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displaygroup {
        get {
            return this.displaygroupField;
        }
        set {
            this.displaygroupField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultcostfactorfriends {
        get {
            return this.defaultcostfactorfriendsField;
        }
        set {
            this.defaultcostfactorfriendsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultcostfactorusers {
        get {
            return this.defaultcostfactorusersField;
        }
        set {
            this.defaultcostfactorusersField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string craftanimation {
        get {
            return this.craftanimationField;
        }
        set {
            this.craftanimationField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconAtlas {
        get {
            return this.iconAtlasField;
        }
        set {
            this.iconAtlasField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconSprite {
        get {
            return this.iconSpriteField;
        }
        set {
            this.iconSpriteField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uispritename {
        get {
            return this.uispritenameField;
        }
        set {
            this.uispritenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uisoundevent {
        get {
            return this.uisoundeventField;
        }
        set {
            this.uisoundeventField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlocked {
        get {
            return this.unlockedField;
        }
        set {
            this.unlockedField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string accessrightspreset {
        get {
            return this.accessrightspresetField;
        }
        set {
            this.accessrightspresetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsMeldbuildingMeldingcombinationsCombination {
    
    private buildingsMeldbuildingMeldingcombinationsCombinationNeededitem[] neededitemField;
    
    private string tierField;
    
    private string powerlevelField;
    
    private string aspectField;
    
    private string timeField;
    
    private string lootlistField;
    

    [System.Xml.Serialization.XmlElementAttribute("neededitem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public buildingsMeldbuildingMeldingcombinationsCombinationNeededitem[] neededitem {
        get {
            return this.neededitemField;
        }
        set {
            this.neededitemField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string powerlevel {
        get {
            return this.powerlevelField;
        }
        set {
            this.powerlevelField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aspect {
        get {
            return this.aspectField;
        }
        set {
            this.aspectField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lootlist {
        get {
            return this.lootlistField;
        }
        set {
            this.lootlistField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsMeldbuildingMeldingcombinationsCombinationNeededitem {
    
    private string uniquenameField;
    
    private string quantityField;
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsPlayerbuilding {
    
    private craftingrequirements[] craftingrequirementsField;
    
    private buildingsPlayerbuildingPlacelaborerLaborer[] placelaborerField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string placecostField;
    
    private string furniturelimitField;
    
    private string residentslimitField;
    
    private string laborerslimitField;
    
    private string upgradeabletoField;
    
    private string durabilityField;
    
    private string durabilitylossField;
    
    private string categoryField;
    
    private string displaygroupField;
    
    private string unlockedField;
    
    private string iconAtlasField;
    
    private string iconSpriteField;
    
    private string uispritenameField;
    
    private string accessrightspresetField;
    
    private string nutritionstorageField;
    
    private string nutritionlossField;
    
    private string repaircostfactorField;
    
    private string destructionreturnfactorField;
    
    private string unlockedbyfounderstateField;
    
    private string uisoundeventField;
    

    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("laborer", typeof(buildingsPlayerbuildingPlacelaborerLaborer), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public buildingsPlayerbuildingPlacelaborerLaborer[] placelaborer {
        get {
            return this.placelaborerField;
        }
        set {
            this.placelaborerField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placecost {
        get {
            return this.placecostField;
        }
        set {
            this.placecostField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string furniturelimit {
        get {
            return this.furniturelimitField;
        }
        set {
            this.furniturelimitField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string residentslimit {
        get {
            return this.residentslimitField;
        }
        set {
            this.residentslimitField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string laborerslimit {
        get {
            return this.laborerslimitField;
        }
        set {
            this.laborerslimitField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string upgradeableto {
        get {
            return this.upgradeabletoField;
        }
        set {
            this.upgradeabletoField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durability {
        get {
            return this.durabilityField;
        }
        set {
            this.durabilityField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durabilityloss {
        get {
            return this.durabilitylossField;
        }
        set {
            this.durabilitylossField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displaygroup {
        get {
            return this.displaygroupField;
        }
        set {
            this.displaygroupField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlocked {
        get {
            return this.unlockedField;
        }
        set {
            this.unlockedField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconAtlas {
        get {
            return this.iconAtlasField;
        }
        set {
            this.iconAtlasField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconSprite {
        get {
            return this.iconSpriteField;
        }
        set {
            this.iconSpriteField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uispritename {
        get {
            return this.uispritenameField;
        }
        set {
            this.uispritenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string accessrightspreset {
        get {
            return this.accessrightspresetField;
        }
        set {
            this.accessrightspresetField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionstorage {
        get {
            return this.nutritionstorageField;
        }
        set {
            this.nutritionstorageField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionloss {
        get {
            return this.nutritionlossField;
        }
        set {
            this.nutritionlossField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string repaircostfactor {
        get {
            return this.repaircostfactorField;
        }
        set {
            this.repaircostfactorField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string destructionreturnfactor {
        get {
            return this.destructionreturnfactorField;
        }
        set {
            this.destructionreturnfactorField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlockedbyfounderstate {
        get {
            return this.unlockedbyfounderstateField;
        }
        set {
            this.unlockedbyfounderstateField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uisoundevent {
        get {
            return this.uisoundeventField;
        }
        set {
            this.uisoundeventField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsPlayerbuildingPlacelaborerLaborer {
    
    private string uniquenameField;
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsRepairbuilding {
    
    private favoritedishDish[] favoritedishField;
    
    private craftingrequirements[] craftingrequirementsField;
    
    private AudioInfo[] audioInfoField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string placecostField;
    
    private string upgradeabletoField;
    
    private string durabilityField;
    
    private string durabilitylossField;
    
    private string nutritionstorageField;
    
    private string nutritionlossField;
    
    private string craftcapacityField;
    
    private string craftcapacityregenerationField;
    
    private string categoryField;
    
    private string displaygroupField;
    
    private string defaultcostfactorfriendsField;
    
    private string defaultcostfactorusersField;
    
    private string unlockedField;
    
    private string iconAtlasField;
    
    private string iconSpriteField;
    
    private string uispritenameField;
    
    private string repaircostfactorField;
    
    private string destructionreturnfactorField;
    
    private string uisoundeventField;
    

    [System.Xml.Serialization.XmlArrayItemAttribute("dish", typeof(favoritedishDish), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public favoritedishDish[] favoritedish {
        get {
            return this.favoritedishField;
        }
        set {
            this.favoritedishField = value;
        }
    }
    

    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlElementAttribute("AudioInfo")]
    public AudioInfo[] AudioInfo {
        get {
            return this.audioInfoField;
        }
        set {
            this.audioInfoField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placecost {
        get {
            return this.placecostField;
        }
        set {
            this.placecostField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string upgradeableto {
        get {
            return this.upgradeabletoField;
        }
        set {
            this.upgradeabletoField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durability {
        get {
            return this.durabilityField;
        }
        set {
            this.durabilityField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durabilityloss {
        get {
            return this.durabilitylossField;
        }
        set {
            this.durabilitylossField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionstorage {
        get {
            return this.nutritionstorageField;
        }
        set {
            this.nutritionstorageField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionloss {
        get {
            return this.nutritionlossField;
        }
        set {
            this.nutritionlossField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string craftcapacity {
        get {
            return this.craftcapacityField;
        }
        set {
            this.craftcapacityField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string craftcapacityregeneration {
        get {
            return this.craftcapacityregenerationField;
        }
        set {
            this.craftcapacityregenerationField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displaygroup {
        get {
            return this.displaygroupField;
        }
        set {
            this.displaygroupField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultcostfactorfriends {
        get {
            return this.defaultcostfactorfriendsField;
        }
        set {
            this.defaultcostfactorfriendsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultcostfactorusers {
        get {
            return this.defaultcostfactorusersField;
        }
        set {
            this.defaultcostfactorusersField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlocked {
        get {
            return this.unlockedField;
        }
        set {
            this.unlockedField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconAtlas {
        get {
            return this.iconAtlasField;
        }
        set {
            this.iconAtlasField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconSprite {
        get {
            return this.iconSpriteField;
        }
        set {
            this.iconSpriteField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uispritename {
        get {
            return this.uispritenameField;
        }
        set {
            this.uispritenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string repaircostfactor {
        get {
            return this.repaircostfactorField;
        }
        set {
            this.repaircostfactorField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string destructionreturnfactor {
        get {
            return this.destructionreturnfactorField;
        }
        set {
            this.destructionreturnfactorField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uisoundevent {
        get {
            return this.uisoundeventField;
        }
        set {
            this.uisoundeventField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class buildingsTutorialbuilding {
    
    private craftingrequirements[] craftingrequirementsField;
    
    private AudioInfo[] audioInfoField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string nutritionstorageField;
    
    private string nutritionlossField;
    
    private string iconAtlasField;
    
    private string iconSpriteField;
    
    private string uispritenameField;
    
    private string uinpcspritenameField;
    
    private string uisoundeventField;
    
    private string accessrightspresetField;
    
    private string repaircostfactorField;
    
    private string destructionreturnfactorField;
    
    private string initialnutritionField;
    
    private string upgradeabletoField;
    

    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    

    [System.Xml.Serialization.XmlElementAttribute("AudioInfo")]
    public AudioInfo[] AudioInfo {
        get {
            return this.audioInfoField;
        }
        set {
            this.audioInfoField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionstorage {
        get {
            return this.nutritionstorageField;
        }
        set {
            this.nutritionstorageField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionloss {
        get {
            return this.nutritionlossField;
        }
        set {
            this.nutritionlossField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconAtlas {
        get {
            return this.iconAtlasField;
        }
        set {
            this.iconAtlasField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconSprite {
        get {
            return this.iconSpriteField;
        }
        set {
            this.iconSpriteField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uispritename {
        get {
            return this.uispritenameField;
        }
        set {
            this.uispritenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uinpcspritename {
        get {
            return this.uinpcspritenameField;
        }
        set {
            this.uinpcspritenameField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uisoundevent {
        get {
            return this.uisoundeventField;
        }
        set {
            this.uisoundeventField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string accessrightspreset {
        get {
            return this.accessrightspresetField;
        }
        set {
            this.accessrightspresetField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string repaircostfactor {
        get {
            return this.repaircostfactorField;
        }
        set {
            this.repaircostfactorField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string destructionreturnfactor {
        get {
            return this.destructionreturnfactorField;
        }
        set {
            this.destructionreturnfactorField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string initialnutrition {
        get {
            return this.initialnutritionField;
        }
        set {
            this.initialnutritionField = value;
        }
    }
    

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string upgradeableto {
        get {
            return this.upgradeabletoField;
        }
        set {
            this.upgradeabletoField = value;
        }
    }
}
