//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

public interface IItem
{
    string uniquename { get; }
    string shopcategory { get; }
    craftingrequirements[] craftingrequirements { get; }


    string craftingcategory { get; }
}