//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class craftingrequirements {
    
    private craftingrequirementsPlayerfactionstanding[] playerfactionstandingField;
    
    private craftingrequirementsCurrency[] currencyField;
    
    private craftingrequirementsCraftresource[] craftresourceField;
    
    private string silverField;
    
    private string timeField;
    
    private string swaptransactionField;
    
    private string amountcraftedField;
    
    private string craftingfocusField;
    
    private string buildingfilterField;
    
    private string forcesinglecraftField;
    
    private string goldField;
    
    private string compensategoldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("playerfactionstanding", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public craftingrequirementsPlayerfactionstanding[] playerfactionstanding {
        get {
            return this.playerfactionstandingField;
        }
        set {
            this.playerfactionstandingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("currency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public craftingrequirementsCurrency[] currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("craftresource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public craftingrequirementsCraftresource[] craftresource {
        get {
            return this.craftresourceField;
        }
        set {
            this.craftresourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string silver {
        get {
            return this.silverField;
        }
        set {
            this.silverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string swaptransaction {
        get {
            return this.swaptransactionField;
        }
        set {
            this.swaptransactionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string amountcrafted {
        get {
            return this.amountcraftedField;
        }
        set {
            this.amountcraftedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string craftingfocus {
        get {
            return this.craftingfocusField;
        }
        set {
            this.craftingfocusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string buildingfilter {
        get {
            return this.buildingfilterField;
        }
        set {
            this.buildingfilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string forcesinglecraft {
        get {
            return this.forcesinglecraftField;
        }
        set {
            this.forcesinglecraftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gold {
        get {
            return this.goldField;
        }
        set {
            this.goldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string compensategold {
        get {
            return this.compensategoldField;
        }
        set {
            this.compensategoldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class craftingrequirementsPlayerfactionstanding {
    
    private string factionField;
    
    private string minstandingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string faction {
        get {
            return this.factionField;
        }
        set {
            this.factionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minstanding {
        get {
            return this.minstandingField;
        }
        set {
            this.minstandingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class craftingrequirementsCurrency {
    
    private string uniquenameField;
    
    private string amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class craftingrequirementsCraftresource {
    
    private string uniquenameField;
    
    private string countField;
    
    private string maxreturnamountField;
    
    private string enchantmentlevelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxreturnamount {
        get {
            return this.maxreturnamountField;
        }
        set {
            this.maxreturnamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string enchantmentlevel {
        get {
            return this.enchantmentlevelField;
        }
        set {
            this.enchantmentlevelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class AudioInfo {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class enchantments {
    
    private enchantmentsEnchantment[] enchantmentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("enchantment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public enchantmentsEnchantment[] enchantment {
        get {
            return this.enchantmentField;
        }
        set {
            this.enchantmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class enchantmentsEnchantment {
    
    private craftingrequirements[] craftingrequirementsField;
    
    private enchantmentsEnchantmentUpgraderequirementsUpgraderesource[] upgraderequirementsField;
    
    private string enchantmentlevelField;
    
    private string abilitypowerField;
    
    private string dummyitempowerField;
    
    private string consumespellField;
    
    private string nutritionField;
    
    private string weightField;
    
    private string itempowerField;
    
    private string durabilityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("upgraderesource", typeof(enchantmentsEnchantmentUpgraderequirementsUpgraderesource), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public enchantmentsEnchantmentUpgraderequirementsUpgraderesource[] upgraderequirements {
        get {
            return this.upgraderequirementsField;
        }
        set {
            this.upgraderequirementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string enchantmentlevel {
        get {
            return this.enchantmentlevelField;
        }
        set {
            this.enchantmentlevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string abilitypower {
        get {
            return this.abilitypowerField;
        }
        set {
            this.abilitypowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dummyitempower {
        get {
            return this.dummyitempowerField;
        }
        set {
            this.dummyitempowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string consumespell {
        get {
            return this.consumespellField;
        }
        set {
            this.consumespellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutrition {
        get {
            return this.nutritionField;
        }
        set {
            this.nutritionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string itempower {
        get {
            return this.itempowerField;
        }
        set {
            this.itempowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durability {
        get {
            return this.durabilityField;
        }
        set {
            this.durabilityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class enchantmentsEnchantmentUpgraderequirementsUpgraderesource {
    
    private string uniquenameField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SocketPreset {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class AssetVfxPreset {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class craftingspelllist {
    
    private craftingspelllistCraftspell[] craftspellField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("craftspell", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public craftingspelllistCraftspell[] craftspell {
        get {
            return this.craftspellField;
        }
        set {
            this.craftspellField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class craftingspelllistCraftspell {
    
    private string uniquenameField;
    
    private string slotsField;
    
    private string tagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slots {
        get {
            return this.slotsField;
        }
        set {
            this.slotsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag {
        get {
            return this.tagField;
        }
        set {
            this.tagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class validitem {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class items {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AssetVfxPreset", typeof(AssetVfxPreset))]
    [System.Xml.Serialization.XmlElementAttribute("AudioInfo", typeof(AudioInfo))]
    [System.Xml.Serialization.XmlElementAttribute("SocketPreset", typeof(SocketPreset))]
    [System.Xml.Serialization.XmlElementAttribute("consumablefrominventoryitem", typeof(itemsConsumablefrominventoryitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("consumableitem", typeof(itemsConsumableitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements", typeof(craftingrequirements))]
    [System.Xml.Serialization.XmlElementAttribute("craftingspelllist", typeof(craftingspelllist))]
    [System.Xml.Serialization.XmlElementAttribute("enchantments", typeof(enchantments))]
    [System.Xml.Serialization.XmlElementAttribute("equipmentitem", typeof(itemsEquipmentitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("farmableitem", typeof(itemsFarmableitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("furnitureitem", typeof(itemsFurnitureitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("journalitem", typeof(itemsJournalitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("mount", typeof(itemsMount), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("simpleitem", typeof(itemsSimpleitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("validitem", typeof(validitem))]
    [System.Xml.Serialization.XmlElementAttribute("weapon", typeof(itemsWeapon), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsConsumablefrominventoryitem {
    
    private craftingrequirements[] craftingrequirementsField;
    
    private AudioInfo[] audioInfoField;
    
    private string uniquenameField;
    
    private string tradableField;
    
    private string uispriteField;
    
    private string abilitypowerField;
    
    private string consumespellField;
    
    private string shopcategoryField;
    
    private string shopsubcategory1Field;
    
    private string tierField;
    
    private string weightField;
    
    private string dummyitempowerField;
    
    private string maxstacksizeField;
    
    private string unlockedtocraftField;
    
    private string uicraftsoundstartField;
    
    private string uicraftsoundfinishField;
    
    private string itemvalueField;
    
    private string uispriteoverlayField;
    
    private string enchantmentlevelField;
    
    private string descriptionlocatagField;
    
    private string salvageableField;
    
    private string showinmarketplaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AudioInfo")]
    public AudioInfo[] AudioInfo {
        get {
            return this.audioInfoField;
        }
        set {
            this.audioInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tradable {
        get {
            return this.tradableField;
        }
        set {
            this.tradableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uisprite {
        get {
            return this.uispriteField;
        }
        set {
            this.uispriteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string abilitypower {
        get {
            return this.abilitypowerField;
        }
        set {
            this.abilitypowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string consumespell {
        get {
            return this.consumespellField;
        }
        set {
            this.consumespellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shopcategory {
        get {
            return this.shopcategoryField;
        }
        set {
            this.shopcategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shopsubcategory1 {
        get {
            return this.shopsubcategory1Field;
        }
        set {
            this.shopsubcategory1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dummyitempower {
        get {
            return this.dummyitempowerField;
        }
        set {
            this.dummyitempowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxstacksize {
        get {
            return this.maxstacksizeField;
        }
        set {
            this.maxstacksizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlockedtocraft {
        get {
            return this.unlockedtocraftField;
        }
        set {
            this.unlockedtocraftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uicraftsoundstart {
        get {
            return this.uicraftsoundstartField;
        }
        set {
            this.uicraftsoundstartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uicraftsoundfinish {
        get {
            return this.uicraftsoundfinishField;
        }
        set {
            this.uicraftsoundfinishField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string itemvalue {
        get {
            return this.itemvalueField;
        }
        set {
            this.itemvalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uispriteoverlay {
        get {
            return this.uispriteoverlayField;
        }
        set {
            this.uispriteoverlayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string enchantmentlevel {
        get {
            return this.enchantmentlevelField;
        }
        set {
            this.enchantmentlevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string descriptionlocatag {
        get {
            return this.descriptionlocatagField;
        }
        set {
            this.descriptionlocatagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string salvageable {
        get {
            return this.salvageableField;
        }
        set {
            this.salvageableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string showinmarketplace {
        get {
            return this.showinmarketplaceField;
        }
        set {
            this.showinmarketplaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsConsumableitem {
    
    private craftingrequirements[] craftingrequirementsField;
    
    private enchantmentsEnchantment[] enchantmentsField;
    
    private string uniquenameField;
    
    private string fishingfameField;
    
    private string fishingminigamesettingField;
    
    private string descriptionlocatagField;
    
    private string uispriteField;
    
    private string nutritionField;
    
    private string abilitypowerField;
    
    private string slottypeField;
    
    private string consumespellField;
    
    private string shopcategoryField;
    
    private string shopsubcategory1Field;
    
    private string resourcetypeField;
    
    private string tierField;
    
    private string weightField;
    
    private string dummyitempowerField;
    
    private string maxstacksizeField;
    
    private string unlockedtocraftField;
    
    private string unlockedtoequipField;
    
    private string uicraftsoundstartField;
    
    private string uicraftsoundfinishField;
    
    private string uispriteoverlayField;
    
    private string tradableField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("enchantment", typeof(enchantmentsEnchantment), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public enchantmentsEnchantment[] enchantments {
        get {
            return this.enchantmentsField;
        }
        set {
            this.enchantmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fishingfame {
        get {
            return this.fishingfameField;
        }
        set {
            this.fishingfameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fishingminigamesetting {
        get {
            return this.fishingminigamesettingField;
        }
        set {
            this.fishingminigamesettingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string descriptionlocatag {
        get {
            return this.descriptionlocatagField;
        }
        set {
            this.descriptionlocatagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uisprite {
        get {
            return this.uispriteField;
        }
        set {
            this.uispriteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutrition {
        get {
            return this.nutritionField;
        }
        set {
            this.nutritionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string abilitypower {
        get {
            return this.abilitypowerField;
        }
        set {
            this.abilitypowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slottype {
        get {
            return this.slottypeField;
        }
        set {
            this.slottypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string consumespell {
        get {
            return this.consumespellField;
        }
        set {
            this.consumespellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shopcategory {
        get {
            return this.shopcategoryField;
        }
        set {
            this.shopcategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shopsubcategory1 {
        get {
            return this.shopsubcategory1Field;
        }
        set {
            this.shopsubcategory1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resourcetype {
        get {
            return this.resourcetypeField;
        }
        set {
            this.resourcetypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dummyitempower {
        get {
            return this.dummyitempowerField;
        }
        set {
            this.dummyitempowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxstacksize {
        get {
            return this.maxstacksizeField;
        }
        set {
            this.maxstacksizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlockedtocraft {
        get {
            return this.unlockedtocraftField;
        }
        set {
            this.unlockedtocraftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlockedtoequip {
        get {
            return this.unlockedtoequipField;
        }
        set {
            this.unlockedtoequipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uicraftsoundstart {
        get {
            return this.uicraftsoundstartField;
        }
        set {
            this.uicraftsoundstartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uicraftsoundfinish {
        get {
            return this.uicraftsoundfinishField;
        }
        set {
            this.uicraftsoundfinishField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uispriteoverlay {
        get {
            return this.uispriteoverlayField;
        }
        set {
            this.uispriteoverlayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tradable {
        get {
            return this.tradableField;
        }
        set {
            this.tradableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFarmableitem {
    
    private craftingrequirements[] craftingrequirementsField;
    
    private AudioInfo[] audioInfoField;
    
    private itemsFarmableitemHarvest[] harvestField;
    
    private itemsFarmableitemGrownitem[] grownitemField;
    
    private itemsFarmableitemConsumptionFood[] consumptionField;
    
    private itemsFarmableitemProductsProduct[] productsField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string craftfamegainfactorField;
    
    private string placecostField;
    
    private string placefameField;
    
    private string pickupableField;
    
    private string destroyableField;
    
    private string unlockedtoplaceField;
    
    private string maxstacksizeField;
    
    private string shopcategoryField;
    
    private string shopsubcategory1Field;
    
    private string kindField;
    
    private string weightField;
    
    private string unlockedtocraftField;
    
    private string animationidField;
    
    private string activefarmfocuscostField;
    
    private string activefarmmaxcyclesField;
    
    private string activefarmactiondurationsecondsField;
    
    private string activefarmcyclelengthsecondsField;
    
    private string activefarmbonusField;
    
    private string prefabnameField;
    
    private string prefabscaleField;
    
    private string resourcevalueField;
    
    private string tileField;
    
    private string uispriteField;
    
    private string showinmarketplaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AudioInfo")]
    public AudioInfo[] AudioInfo {
        get {
            return this.audioInfoField;
        }
        set {
            this.audioInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("harvest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsFarmableitemHarvest[] harvest {
        get {
            return this.harvestField;
        }
        set {
            this.harvestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("grownitem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsFarmableitemGrownitem[] grownitem {
        get {
            return this.grownitemField;
        }
        set {
            this.grownitemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("food", typeof(itemsFarmableitemConsumptionFood), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public itemsFarmableitemConsumptionFood[] consumption {
        get {
            return this.consumptionField;
        }
        set {
            this.consumptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("product", typeof(itemsFarmableitemProductsProduct), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public itemsFarmableitemProductsProduct[] products {
        get {
            return this.productsField;
        }
        set {
            this.productsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string craftfamegainfactor {
        get {
            return this.craftfamegainfactorField;
        }
        set {
            this.craftfamegainfactorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placecost {
        get {
            return this.placecostField;
        }
        set {
            this.placecostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placefame {
        get {
            return this.placefameField;
        }
        set {
            this.placefameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pickupable {
        get {
            return this.pickupableField;
        }
        set {
            this.pickupableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string destroyable {
        get {
            return this.destroyableField;
        }
        set {
            this.destroyableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlockedtoplace {
        get {
            return this.unlockedtoplaceField;
        }
        set {
            this.unlockedtoplaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxstacksize {
        get {
            return this.maxstacksizeField;
        }
        set {
            this.maxstacksizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shopcategory {
        get {
            return this.shopcategoryField;
        }
        set {
            this.shopcategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shopsubcategory1 {
        get {
            return this.shopsubcategory1Field;
        }
        set {
            this.shopsubcategory1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlockedtocraft {
        get {
            return this.unlockedtocraftField;
        }
        set {
            this.unlockedtocraftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string animationid {
        get {
            return this.animationidField;
        }
        set {
            this.animationidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string activefarmfocuscost {
        get {
            return this.activefarmfocuscostField;
        }
        set {
            this.activefarmfocuscostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string activefarmmaxcycles {
        get {
            return this.activefarmmaxcyclesField;
        }
        set {
            this.activefarmmaxcyclesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string activefarmactiondurationseconds {
        get {
            return this.activefarmactiondurationsecondsField;
        }
        set {
            this.activefarmactiondurationsecondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string activefarmcyclelengthseconds {
        get {
            return this.activefarmcyclelengthsecondsField;
        }
        set {
            this.activefarmcyclelengthsecondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string activefarmbonus {
        get {
            return this.activefarmbonusField;
        }
        set {
            this.activefarmbonusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prefabname {
        get {
            return this.prefabnameField;
        }
        set {
            this.prefabnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prefabscale {
        get {
            return this.prefabscaleField;
        }
        set {
            this.prefabscaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resourcevalue {
        get {
            return this.resourcevalueField;
        }
        set {
            this.resourcevalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tile {
        get {
            return this.tileField;
        }
        set {
            this.tileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uisprite {
        get {
            return this.uispriteField;
        }
        set {
            this.uispriteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string showinmarketplace {
        get {
            return this.showinmarketplaceField;
        }
        set {
            this.showinmarketplaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFarmableitemHarvest {
    
    private itemsFarmableitemHarvestSeed[] seedField;
    
    private string growtimeField;
    
    private string lootlistField;
    
    private string lootchanceField;
    
    private string fameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("seed", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsFarmableitemHarvestSeed[] seed {
        get {
            return this.seedField;
        }
        set {
            this.seedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string growtime {
        get {
            return this.growtimeField;
        }
        set {
            this.growtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lootlist {
        get {
            return this.lootlistField;
        }
        set {
            this.lootlistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lootchance {
        get {
            return this.lootchanceField;
        }
        set {
            this.lootchanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fame {
        get {
            return this.fameField;
        }
        set {
            this.fameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFarmableitemHarvestSeed {
    
    private string chanceField;
    
    private string amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string chance {
        get {
            return this.chanceField;
        }
        set {
            this.chanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFarmableitemGrownitem {
    
    private itemsFarmableitemGrownitemOffspring[] offspringField;
    
    private string uniquenameField;
    
    private string growtimeField;
    
    private string fameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("offspring", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsFarmableitemGrownitemOffspring[] offspring {
        get {
            return this.offspringField;
        }
        set {
            this.offspringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string growtime {
        get {
            return this.growtimeField;
        }
        set {
            this.growtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fame {
        get {
            return this.fameField;
        }
        set {
            this.fameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFarmableitemGrownitemOffspring {
    
    private string chanceField;
    
    private string amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string chance {
        get {
            return this.chanceField;
        }
        set {
            this.chanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFarmableitemConsumptionFood {
    
    private itemsFarmableitemConsumptionFoodAcceptedfood[] acceptedfoodField;
    
    private string nutritionmaxField;
    
    private string secondspernutritionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("acceptedfood", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsFarmableitemConsumptionFoodAcceptedfood[] acceptedfood {
        get {
            return this.acceptedfoodField;
        }
        set {
            this.acceptedfoodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nutritionmax {
        get {
            return this.nutritionmaxField;
        }
        set {
            this.nutritionmaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string secondspernutrition {
        get {
            return this.secondspernutritionField;
        }
        set {
            this.secondspernutritionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFarmableitemConsumptionFoodAcceptedfood {
    
    private string foodcategoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string foodcategory {
        get {
            return this.foodcategoryField;
        }
        set {
            this.foodcategoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFarmableitemProductsProduct {
    
    private string productiontimeField;
    
    private string actionnameField;
    
    private string lootlistField;
    
    private string lootchanceField;
    
    private string fameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string productiontime {
        get {
            return this.productiontimeField;
        }
        set {
            this.productiontimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string actionname {
        get {
            return this.actionnameField;
        }
        set {
            this.actionnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lootlist {
        get {
            return this.lootlistField;
        }
        set {
            this.lootlistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lootchance {
        get {
            return this.lootchanceField;
        }
        set {
            this.lootchanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fame {
        get {
            return this.fameField;
        }
        set {
            this.fameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFurnitureitem {
    
    private string cheatproviderField;
    
    private craftingrequirements[] craftingrequirementsField;
    
    private itemsFurnitureitemContainer[] containerField;
    
    private itemsFurnitureitemRepairkit[] repairkitField;
    
    private string uniquenameField;
    
    private string shopcategoryField;
    
    private string shopsubcategory1Field;
    
    private string tierField;
    
    private string durabilityField;
    
    private string durabilitylossperdayfactorField;
    
    private string weightField;
    
    private string unlockedtocraftField;
    
    private string placeableindoorsField;
    
    private string placeableoutdoorsField;
    
    private string placeableindungeonsField;
    
    private string accessrightspresetField;
    
    private string uicraftsoundstartField;
    
    private string uicraftsoundfinishField;
    
    private string customizewithguildlogoField;
    
    private string enchantmentlevelField;
    
    private string uispriteField;
    
    private string tileField;
    
    private string itemvalueField;
    
    private string showinmarketplaceField;
    
    private string residencyslotsField;
    
    private string labourerfurnituretypeField;
    
    private string labourersaffectedField;
    
    private string labourerhappinessField;
    
    private string labourersperfurnitureitemField;
    
    private string placeableonlyonislandsField;
    
    private string descriptionlocatagField;
    
    private string craftfamegainfactorField;
    
    private string durabilitylossperusefactorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cheatprovider {
        get {
            return this.cheatproviderField;
        }
        set {
            this.cheatproviderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("container", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsFurnitureitemContainer[] container {
        get {
            return this.containerField;
        }
        set {
            this.containerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("repairkit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsFurnitureitemRepairkit[] repairkit {
        get {
            return this.repairkitField;
        }
        set {
            this.repairkitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shopcategory {
        get {
            return this.shopcategoryField;
        }
        set {
            this.shopcategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shopsubcategory1 {
        get {
            return this.shopsubcategory1Field;
        }
        set {
            this.shopsubcategory1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durability {
        get {
            return this.durabilityField;
        }
        set {
            this.durabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durabilitylossperdayfactor {
        get {
            return this.durabilitylossperdayfactorField;
        }
        set {
            this.durabilitylossperdayfactorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlockedtocraft {
        get {
            return this.unlockedtocraftField;
        }
        set {
            this.unlockedtocraftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placeableindoors {
        get {
            return this.placeableindoorsField;
        }
        set {
            this.placeableindoorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placeableoutdoors {
        get {
            return this.placeableoutdoorsField;
        }
        set {
            this.placeableoutdoorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placeableindungeons {
        get {
            return this.placeableindungeonsField;
        }
        set {
            this.placeableindungeonsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string accessrightspreset {
        get {
            return this.accessrightspresetField;
        }
        set {
            this.accessrightspresetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uicraftsoundstart {
        get {
            return this.uicraftsoundstartField;
        }
        set {
            this.uicraftsoundstartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uicraftsoundfinish {
        get {
            return this.uicraftsoundfinishField;
        }
        set {
            this.uicraftsoundfinishField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string customizewithguildlogo {
        get {
            return this.customizewithguildlogoField;
        }
        set {
            this.customizewithguildlogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string enchantmentlevel {
        get {
            return this.enchantmentlevelField;
        }
        set {
            this.enchantmentlevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uisprite {
        get {
            return this.uispriteField;
        }
        set {
            this.uispriteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tile {
        get {
            return this.tileField;
        }
        set {
            this.tileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string itemvalue {
        get {
            return this.itemvalueField;
        }
        set {
            this.itemvalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string showinmarketplace {
        get {
            return this.showinmarketplaceField;
        }
        set {
            this.showinmarketplaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string residencyslots {
        get {
            return this.residencyslotsField;
        }
        set {
            this.residencyslotsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string labourerfurnituretype {
        get {
            return this.labourerfurnituretypeField;
        }
        set {
            this.labourerfurnituretypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string labourersaffected {
        get {
            return this.labourersaffectedField;
        }
        set {
            this.labourersaffectedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string labourerhappiness {
        get {
            return this.labourerhappinessField;
        }
        set {
            this.labourerhappinessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string labourersperfurnitureitem {
        get {
            return this.labourersperfurnitureitemField;
        }
        set {
            this.labourersperfurnitureitemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placeableonlyonislands {
        get {
            return this.placeableonlyonislandsField;
        }
        set {
            this.placeableonlyonislandsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string descriptionlocatag {
        get {
            return this.descriptionlocatagField;
        }
        set {
            this.descriptionlocatagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string craftfamegainfactor {
        get {
            return this.craftfamegainfactorField;
        }
        set {
            this.craftfamegainfactorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string durabilitylossperusefactor {
        get {
            return this.durabilitylossperusefactorField;
        }
        set {
            this.durabilitylossperusefactorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFurnitureitemContainer {
    
    private string capacityField;
    
    private string weightlimitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string capacity {
        get {
            return this.capacityField;
        }
        set {
            this.capacityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weightlimit {
        get {
            return this.weightlimitField;
        }
        set {
            this.weightlimitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsFurnitureitemRepairkit {
    
    private string repaircostfactorField;
    
    private string maxtierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string repaircostfactor {
        get {
            return this.repaircostfactorField;
        }
        set {
            this.repaircostfactorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxtier {
        get {
            return this.maxtierField;
        }
        set {
            this.maxtierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsJournalitem {
    
    private craftingrequirements[] craftingrequirementsField;
    
    private itemsJournalitemFamefillingmissions[] famefillingmissionsField;
    
    private itemsJournalitemLootlistLoot[] lootlistField;
    
    private string salvageableField;
    
    private string uniquenameField;
    
    private string tierField;
    
    private string maxfameField;
    
    private string baselootamountField;
    
    private string shopcategoryField;
    
    private string shopsubcategory1Field;
    
    private string weightField;
    
    private string unlockedtocraftField;
    
    private string craftfamegainfactorField;
    
    private string fasttravelfactorField;
    
    private string uispriteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("craftingrequirements")]
    public craftingrequirements[] craftingrequirements {
        get {
            return this.craftingrequirementsField;
        }
        set {
            this.craftingrequirementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("famefillingmissions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsJournalitemFamefillingmissions[] famefillingmissions {
        get {
            return this.famefillingmissionsField;
        }
        set {
            this.famefillingmissionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("loot", typeof(itemsJournalitemLootlistLoot), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public itemsJournalitemLootlistLoot[] lootlist {
        get {
            return this.lootlistField;
        }
        set {
            this.lootlistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string salvageable {
        get {
            return this.salvageableField;
        }
        set {
            this.salvageableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxfame {
        get {
            return this.maxfameField;
        }
        set {
            this.maxfameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string baselootamount {
        get {
            return this.baselootamountField;
        }
        set {
            this.baselootamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shopcategory {
        get {
            return this.shopcategoryField;
        }
        set {
            this.shopcategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shopsubcategory1 {
        get {
            return this.shopsubcategory1Field;
        }
        set {
            this.shopsubcategory1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unlockedtocraft {
        get {
            return this.unlockedtocraftField;
        }
        set {
            this.unlockedtocraftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string craftfamegainfactor {
        get {
            return this.craftfamegainfactorField;
        }
        set {
            this.craftfamegainfactorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fasttravelfactor {
        get {
            return this.fasttravelfactorField;
        }
        set {
            this.fasttravelfactorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uisprite {
        get {
            return this.uispriteField;
        }
        set {
            this.uispriteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsJournalitemFamefillingmissions {
    
    private itemsJournalitemFamefillingmissionsFishingfame[] fishingfameField;
    
    private itemsJournalitemFamefillingmissionsFameearned[] fameearnedField;
    
    private itemsJournalitemFamefillingmissionsKillmobfame[] killmobfameField;
    
    private itemsJournalitemFamefillingmissionsCraftitemfame[] craftitemfameField;
    
    private itemsJournalitemFamefillingmissionsGatherfame[] gatherfameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fishingfame", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsJournalitemFamefillingmissionsFishingfame[] fishingfame {
        get {
            return this.fishingfameField;
        }
        set {
            this.fishingfameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fameearned", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsJournalitemFamefillingmissionsFameearned[] fameearned {
        get {
            return this.fameearnedField;
        }
        set {
            this.fameearnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("killmobfame", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsJournalitemFamefillingmissionsKillmobfame[] killmobfame {
        get {
            return this.killmobfameField;
        }
        set {
            this.killmobfameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("craftitemfame", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsJournalitemFamefillingmissionsCraftitemfame[] craftitemfame {
        get {
            return this.craftitemfameField;
        }
        set {
            this.craftitemfameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gatherfame", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsJournalitemFamefillingmissionsGatherfame[] gatherfame {
        get {
            return this.gatherfameField;
        }
        set {
            this.gatherfameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsJournalitemFamefillingmissionsFishingfame {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsJournalitemFamefillingmissionsFameearned {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsJournalitemFamefillingmissionsKillmobfame {
    
    private string mintierField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mintier {
        get {
            return this.mintierField;
        }
        set {
            this.mintierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsJournalitemFamefillingmissionsCraftitemfame {
    
    private validitem[] validitemField;
    
    private string mintierField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("validitem")]
    public validitem[] validitem {
        get {
            return this.validitemField;
        }
        set {
            this.validitemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mintier {
        get {
            return this.mintierField;
        }
        set {
            this.mintierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsJournalitemFamefillingmissionsGatherfame {
    
    private validitem[] validitemField;
    
    private string mintierField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("validitem")]
    public validitem[] validitem {
        get {
            return this.validitemField;
        }
        set {
            this.validitemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mintier {
        get {
            return this.mintierField;
        }
        set {
            this.mintierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsJournalitemLootlistLoot {
    
    private string itemnameField;
    
    private string itemamountField;
    
    private string weightField;
    
    private string labourerfameField;
    
    private string itemenchantmentlevelField;
    
    private string silveramountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string itemname {
        get {
            return this.itemnameField;
        }
        set {
            this.itemnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string itemamount {
        get {
            return this.itemamountField;
        }
        set {
            this.itemamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string labourerfame {
        get {
            return this.labourerfameField;
        }
        set {
            this.labourerfameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string itemenchantmentlevel {
        get {
            return this.itemenchantmentlevelField;
        }
        set {
            this.itemenchantmentlevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string silveramount {
        get {
            return this.silveramountField;
        }
        set {
            this.silveramountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsMountFootStepVfxPreset {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsMountMountspelllistMountspell {
    
    private string uniquenameField;
    
    private string spellslotField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string spellslot {
        get {
            return this.spellslotField;
        }
        set {
            this.spellslotField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsSimpleitemReplaceondeathReplacementitem {
    
    private string uniquenameField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniquename {
        get {
            return this.uniquenameField;
        }
        set {
            this.uniquenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsWeaponProjectile {
    
    private itemsWeaponProjectileImpactvfx[] impactvfxField;
    
    private AudioInfo[] audioInfoField;
    
    private string prefabField;
    
    private string startsocketField;
    
    private string hitsocketField;
    
    private string timeoffsetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("impactvfx", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemsWeaponProjectileImpactvfx[] impactvfx {
        get {
            return this.impactvfxField;
        }
        set {
            this.impactvfxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AudioInfo")]
    public AudioInfo[] AudioInfo {
        get {
            return this.audioInfoField;
        }
        set {
            this.audioInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prefab {
        get {
            return this.prefabField;
        }
        set {
            this.prefabField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string startsocket {
        get {
            return this.startsocketField;
        }
        set {
            this.startsocketField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hitsocket {
        get {
            return this.hitsocketField;
        }
        set {
            this.hitsocketField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string timeoffset {
        get {
            return this.timeoffsetField;
        }
        set {
            this.timeoffsetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsWeaponProjectileImpactvfx {
    
    private string prefabField;
    
    private string impactsocketField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prefab {
        get {
            return this.prefabField;
        }
        set {
            this.prefabField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string impactsocket {
        get {
            return this.impactsocketField;
        }
        set {
            this.impactsocketField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class itemsWeaponCanharvest {
    
    private string resourcetypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resourcetype {
        get {
            return this.resourcetypeField;
        }
        set {
            this.resourcetypeField = value;
        }
    }
}
